name: animation_wrappers
description: Animation Wrapper widgets, just wrap the child to be animated with this wrapper widget and that child will be animated.
version: 3.0.0
homepage: https://github.com/jagritjkh/animation_wrappers

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: